instance creation
knowledge
	^self new
		title: 'Knowledge Management' ;
		summary: 'to recover all the knowledge that is embedded in legacy software' ;
		header: 'One of the conclusions of my research was that some tasks,
like evaluating the quality of an architectural design, depend also on information
of a different nature. For example, one may want to decompose a
system according to the various market segments it targets (e.g.,
hotels, hospitals, or schools), or according to internal divisions in the organization
using it (e.g., sales department, logistics department, etc.).
This led me to work with more abstract concepts or consider the knowledge
required from software maintainers to do their work.' ;
		queryWords: #( 'knowledge' ) ;
		yourself