instance creation
migration
	^self new
		title: 'Migration' ;
		header: 'Software systems are highly dependent on their environment.
This is the root cause of the continuous evolution effort that must be spent on them.
Sometimes technical environment changes make it necessary to radically change the implementation of a system, for example to migrate the GUI from one framework to another, or to change a core library used.' ;
		queryWords: #( 'migration' ) ;
		yourself