instance creation
other
	^self new
		title: 'Other' ;
		summary: 'aspects of software maintenance management (software quality, risk management, ...)' ;
		header: 'Beyond the main topics I studied (software rearchitecturing,
software quality, knowledge involved in software maintenance) I also
considered other aspects of the software maintenance ecosystem. For example,
the organization within which the people work or the working processes
this organization enforces.' ;
		queryWords: #( 'other' ) ;
		yourself