instance creation
quality
	^self new
		title: 'Software Quality / Metrics' ;
		summary: 'to measure the maintenance activity and legacy software' ;
		header: 'In software maintenance, the quality of the system (e.g., its source code, its architecture) can greatly impact the time it takes to understand it, or to introduce a new
feature.
In this sense, a good part of my research has been dedicated to software quality metrics and models.' ;
		queryWords: #( 'metric' 'quality' ) ;
		yourself