instance creation
tools
	^self new
		title: 'Tools' ;
		summary: '(including Moose) needed to help managing software evolution' ;
		header: '
	Because software evolution is difficult, tools are needed to help software engineers.
	We developped various tools in this sense, a prominent one being Moose, our platform for software analysis.
It allows to represent software system in a model, to query, manipulate, transform, visualize this model.
Many of our research results were only possible thanks to the tools provided by the platform.' ;
		queryWords: #( #tools ) ;
		yourself