sections
architectureHeader
	   ^ '<p>Systems are initially conceived with a given goal and scope in mind. As they
evolve and new functionalities are added, this goal and scope will typically drift
in unforeseen directions. After some time, it becomes necessary to straighten
things by redefining a new architecture, taking into account the new scope of
the system. I worked on methods to help in this task.</p>'