building
introHtmlPage

	^ '
<p>You will find here my publications organized by topic.
In my <a href="publications.html">publications page</a>, they are presented by type and in chronological order.</p>

<p>My work covers various topics of software maintenance:
<ul>
<li><a href="#archi">software architecture</a> and re-structuring, or how to help re-organizing a legacy software into coherent modules;</li>
<li><a href="#quality">software quality</a>, to measure the maintenance activity and legacy software;</li>
<li><a href="#knwldge">knowledge management</a>, to recover all the knowledge that is embedded in legacy software ; and,</li>
<li><a href="#other">other aspects</a> of software maintenance management (software quality, risk management, ...)</li>
</ul>
</p>'