building
xhtmlHeader
	^ '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Nicolas Anquetil</title>
<link href="main.css" rel="stylesheet" type="text/css" />
<link href="bib.css"   rel="stylesheet" type="text/css"/>
</head>
<body>
		<div id="title">
				<h1><font color="#0183E5">Nicolas Anquetil</font></h1>
	<p>'
	
	 , self xhtmlTitle ,
	
	'</p>
</div>		
		<div id="container">
				<div id="sidebarout">
				<div id="sidebarin">
					<h1>Main Menu</h1>
		
							<div id="menu">
								<a href="nicolasAnquetil.html">Home</a><br />
								<a href="publications.html">Publications</a><br />
								<a href="themes.html">Research themes</a><br />
								<a href="miscAcademy.html">Misc. Academia</a><br />
								<a href="projects.html">Projects</a><br />
								<a href="links.html">External links</a>
				 			</div>

							 <p></p>

							<div id="menu">

<p>Nicolas.Anquetil @ inria.fr<br />
Research office: Room 321, Inria building B, +33 (0)3 59 35 87 47<br />
Teaching Office: Room 3A049, IUT-A, +33 (0)3 20 43 47 14</p>

		 			 </div>
				</div>
				</div>


				<div id="content">
				<h1>Publications</h1>
'